repository:
    path: github.com/Lusitaniae/apache_exporter
build:
    flags: -a -tags netgo
    ldflags: |
        -X main.Version={{.Version}}
        -X main.Branch={{.Branch}}
        -X main.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - LICENSE
